### ISSUE TITLE
INDI driver for Brightstar Mammut Lyuba (or Orion Starshoot G3)

### ISSUE THREAD

**Issue by Manu4810** [indilib/indi-3rdparty#125]
I own an old Brightstar Mammut Lyuba camera which works fine on Windows with both native and ASCOM drivers (that are no more maintained since the company closed business). I would like to move my entire set-up to a full linux environement, with RaspberryPI / Astroberry, but unfortunately the camera is not recognized by the existing set of INDI drivers embedded in Astroberry (I tried MEADE DSI, Orion SSAG, Starshoot, all to no avail) and therefore cannot be used as main or guide camera. This camera ressembles the ORION Starshoot G3 very much. It seems to be based on some AVR32 AMTEL chipset from microchips (so it says from dmesg after plugging it into the USB port). Any advice on the relevant INDI driver to be used or any trick involving ASCOM Alpaca would be very much welcome. Thanks

**Comment by knro** [comment]
So you confirm indi_starshootg_ccd driver does not work with it?

**Comment by Manu4810** [comment]
I'm afraid I do.

**Comment by knro** [comment]
Then there is no support for the camera, and given that there is no SDK and company closed, chances are quite slim unless you are willing to develop a driver for it.

**Comment by bgilsrud** [comment]
@Manu4810 can you provide the USB VID and PID for this device? A few of us are working on a driver for the Orion Starshoot G3 if you care to join us: https://indilib.org/forum/general/878-support-for-orion-starshoot-g3-ccd.html
