### ISSUE TITLE
Queue Report pile up in indi_gpsd

### ISSUE THREAD

**Issue by rtlprmft** [indilib/indi-3rdparty#180]
I am not sure whether this is a general issue or depends on my configuration. I am using a ublox7-usb module with indi_gpsd. When I enable the automatic refresh (1s, 5s, or even manually), for every refresh, the time only increases by only one second. To my understanding, this is because the gpsd delivers a continuous stream and buffers this stream. When the buffer is then read with gps->read() only the next (but not the most recent report gets read. Therefore, I suggest the following change (works for me flewlessly):

Wrap the gps->read()  in w a while loop which makes sure that the queue is empty:

    while (1)
    {
        if ((gpsData = gps->read()) == nullptr)
        {
            LOG_ERROR("GPSD read error.");
            IDSetText(&GPSstatusTP, nullptr);
            return IPS_ALERT;
        }

        if (!gps->waiting(0))
            break;
    }

**Comment by knro** [comment]
Thank you, I noticed this issue too. 

@rkaczorek What do you think?

**Comment by rkaczorek** [comment]
Seems reasonable to me. @rtlprmft could you submit PR so I can review complete change?

**Comment by jochym** [comment]
That is an obvious bug. I second the need for a fix. If you have a a patch for that @rtlprmft please submit a PR, otherwise we (authors of gpsd) need to fix this.

**Comment by rtlprmft** [comment]
I am sorry, but I have no idea how to do so. Code snippet that solves the problem (empties the queue) is above. I am happy for any advice.

**Comment by rkaczorek** [comment]
@jochym are you going to handle it?

**Comment by jochym** [comment]
@rkaczorek I'll do it today
