### ISSUE TITLE
Build issue on ShelYak with CircleCI

### ISSUE THREAD

**Issue by thx8411** [indilib/indi-3rdparty#197]
Hello,

Build issue on the ChelYak driver with CircleCi.

Link AtroLink4, just warnings, but it kills the job.

<<
Scanning dependencies of target indi_shelyakspox_spectrograph

[ 24%] Building CXX object indi-shelyak/CMakeFiles/indi_shelyakspox_spectrograph.dir/indi_shelyakspox_spectrograph.cpp.o

/root/project/indi-shelyak/indi_shelyakspox_spectrograph.cpp: In member function 'virtual bool ShelyakSpox::Connect()':

/root/project/indi-shelyak/indi_shelyakspox_spectrograph.cpp:169:9: error: unused variable 'tty_rc' [-Werror=unused-variable]

     int tty_rc = tty_nread_section(PortFD, line, 80, 0x0a, 3, &bytes_read);

         ^~~~~~

/root/project/indi-shelyak/indi_shelyakspox_spectrograph.cpp: In member function 'bool ShelyakSpox::calibrationUnitCommand(char, char)':

/root/project/indi-shelyak/indi_shelyakspox_spectrograph.cpp:384:13: error: this statement may fall through [-Werror=implicit-fallthrough=]

             }

             ^

/root/project/indi-shelyak/indi_shelyakspox_spectrograph.cpp:387:9: note: here

         case 0x30 : { //SKY button

         ^~~~

cc1plus: all warnings being treated as errors

indi-shelyak/CMakeFiles/indi_shelyakspox_spectrograph.dir/build.make:62: recipe for target 'indi-shelyak/CMakeFiles/indi_shelyakspox_spectrograph.dir/indi_shelyakspox_spectrograph.cpp.o' failed

make[2]: *** [indi-shelyak/CMakeFiles/indi_shelyakspox_spectrograph.dir/indi_shelyakspox_spectrograph.cpp.o] Error 1

CMakeFiles/Makefile2:855: recipe for target 'indi-shelyak/CMakeFiles/indi_shelyakspox_spectrograph.dir/all' failed

make[1]: *** [indi-shelyak/CMakeFiles/indi_shelyakspox_spectrograph.dir/all] Error 2

Makefile:151: recipe for target 'all' failed

make: *** [all] Error 2
>>

Best regards,

Blaise

**Comment by pawel-soja** [comment]
I think the problem is solved. @knro you can close issue.
I will make fixes for the warnings.
