### ISSUE TITLE
Build issue on Pentax driver with CircleCI

### ISSUE THREAD

**Issue by thx8411** [indilib/indi-3rdparty#199]
Hello,

There is a build issue on the Pentax driver (libpktriggercord
[pentax_build.log](https://github.com/indilib/indi-3rdparty/files/5108945/pentax_build.log)
) using CircleCI.
As usual, warnings treated as errors, killing the job.
(cf. attached file)

Best regards,

Blaise

**Comment by pawel-soja** [comment]
I think the problem is solved. @knro you can close issue.
