### ISSUE TITLE
Build issue on AHP driver with CircleCI

### ISSUE THREAD

**Issue by thx8411** [indilib/indi-3rdparty#200]
Hello,

There is a build issue on the AHP driver with CircleCI.
As usual, warnings treated as errors.

<<
Scanning dependencies of target indi_ahp_correlator

[100%] Building CXX object indi-ahp-correlator/CMakeFiles/indi_ahp_correlator.dir/indi_ahp_correlator.cpp.o

/root/project/indi-ahp-correlator/indi_ahp_correlator.cpp: In member function 'void Interferometer::Callback()':

/root/project/indi-ahp-correlator/indi_ahp_correlator.cpp:169:62: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]

             delay_clocks = (delay_clocks > 0 ? (delay_clocks < DELAY_LINES ? delay_clocks : DELAY_LINES-1) : 0);

                                                 ~~~~~~~~~~~~~^~~~~~~~~~~~~

/root/project/indi-ahp-correlator/indi_ahp_correlator.cpp: In member function 'bool Interferometer::Handshake()':

/root/project/indi-ahp-correlator/indi_ahp_correlator.cpp:677:13: error: unused variable 'tmp' [-Werror=unused-variable]

         int tmp = 0;

             ^~~

cc1plus: all warnings being treated as errors

indi-ahp-correlator/CMakeFiles/indi_ahp_correlator.dir/build.make:62: recipe for target 'indi-ahp-correlator/CMakeFiles/indi_ahp_correlator.dir/indi_ahp_correlator.cpp.o' failed

make[2]: *** [indi-ahp-correlator/CMakeFiles/indi_ahp_correlator.dir/indi_ahp_correlator.cpp.o] Error 1

CMakeFiles/Makefile2:3017: recipe for target 'indi-ahp-correlator/CMakeFiles/indi_ahp_correlator.dir/all' failed

make[1]: *** [indi-ahp-correlator/CMakeFiles/indi_ahp_correlator.dir/all] Error 2

Makefile:151: recipe for target 'all' failed

make: *** [all] Error 2
>>

Best regards,

Blaise

**Comment by pawel-soja** [comment]
I think the problem is solved. @knro you can close issue.
I will make fixes for the warnings.
