### ISSUE TITLE
Build issue on ToupBase driver with CircleCI

### ISSUE THREAD

**Issue by thx8411** [indilib/indi-3rdparty#201]
Hello,

Build issue on the ToupBase build with CirlceCI.
As usual, warnings treated as errors, killing the job.

[toupbase_build.log](https://github.com/indilib/indi-3rdparty/files/5109010/toupbase_build.log)

Best regards,

Blaise

**Comment by pawel-soja** [comment]
I think the problem is solved. @knro you can close issue.
I will make fixes for the warnings.
