### ISSUE TITLE
SBIG STF-402 camera not supported by downlevel armhf libsbigudrv2 package

### ISSUE THREAD

**Issue by garlick** [indilib/indi-3rdparty#204]
Apparently the SBIG STF-402 camera requires universal driver version 4.99, as documented in garlick/sbig-util#45.

I think the armhf library that is currently in the repo is 4.84 while the other architectures moved forward to 4.99.  As I understand it, the reason for this was a build problem alluded to in #24, [this comment](https://github.com/indilib/indi-3rdparty/issues/24#issuecomment-553723427).

I _think_ there may be a working armhf build posted here:
 https://forum.diffractionlimited.com/threads/linux-drivers-for-arm-v8-64bit.6290/

Edit: I should say that we tested the armhf binary extracted from the posted deb on raspbian buster and it didn't have any dependency problems.  Perhaps it is broken on ubuntu 32 bit?

Since astroberry is shipping the INDI libsbigudrv2 package for armhf, this camera won't work with astroberry.  Sadness occurs.  Same problem with sbig-util, a set of command line utilities for these cameras that I maintain, when run on raspbian 32 bit.

I realize having these libraries built on request using opaque processes and posted privately is not an optimal arrangment!   Your efforts to put these in a "normal" package are really appreciated.  Especially when they work :-)  Thanks in advance.

**Comment by rkaczorek** [comment]
@knro it looks like commit a1686d6a04effa0ae2c155910a431907dcb61052 included older version of sbig libs than intended.
See [forum post](https://indilib.org/forum/astroberry/7561-sbig-st-402-on-astroberry-fixed-using-raspian-non-astroberry-driver.html#58850) for details.

**Comment by knro** [comment]
So actually, the armhf was not updated due to dependency on GLIBC 2.28 which was not widespread at that time. I think it's acceptable now to have it in the repo but it will no longer work on older distributions.

**Comment by garlick** [comment]
Thanks!  Confirmed problem solved on current master.
