### ISSUE TITLE
lindi_gphoto_ccd doesn't report canon DSLR sensor temperature any more

### ISSUE THREAD

**Issue by thx8411** [indilib/indi-3rdparty#300]
On my ubuntu 18.04 amd64, the indi v1.8.8 indi_gphoto_ccd driver doesn't report the canon DSLR sensor temperature any more
Temp is allways 0

Tested with an EOS 1000D and an EOS M2.

Seem related to the build process.
A new binary, built from sources, works nice.

Official binary size : 154384 -> KO
New binary : 154400 -> OK

My cmake output is attached

[cmake_output.txt](https://github.com/indilib/indi-3rdparty/files/5851911/cmake_output.txt)

**Comment by knro** [comment]
Ok, so this is probably a downstream issue.
