### ISSUE TITLE
[question] does libricohcamerasdk support armv8?

### ISSUE THREAD

**Issue by paolostivanin** [indilib/indi-3rdparty#354]
Hello,
I'm trying to build this package for aarch64 on openSUSE, but I get arch unsupported. It seems that, while it checks for generic `^arm`, it then sets armv7l as arch path.
Does this mean the armv8 is not supported?

Thanks!

https://github.com/indilib/indi-3rdparty/blob/3c40cadd8d1c85c64adc57b694e29bd03f43f7f6/libricohcamerasdk/CMakeLists.txt#L22-L23

**Comment by knro** [comment]
Right, no support unfortunately for arm64.
