### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by pawel-soja** [indilib/indi-3rdparty#378]
Hi!

README.md is probably not valid. I do not see that a catalog with tests.
```
cd ~/Projects/build/indi-3rdparty
cmake -DINDI_BUILD_UNITTESTS=ON -DCMAKE_BUILD_TYPE=Debug ~/Projects/indi-3rdparty
make -j4
cd test
ctest -V
```
When separating the libraries something disappeared?

**Comment by knro** [comment]
I don't recall exactly what happened, but the Google tests were not properly maintained (my fault). It would be great to run all such tests in the CI if possible after each push much like we do for KStars.
