### ISSUE TITLE
ZWO flip param from float to select options

### ISSUE THREAD

**Issue by luzik** [indilib/indi-3rdparty#399]
I believe that flip param in ZWO settings should be INT not float, or float with step 1.0 within range 0-4, or just select with
-do not flip
-flip horizontally
-flip vertically
-flip both

**Comment by knro** [comment]
Right, a switch would make more sense. Then the switch updates the control with the correct value accordingly.

**Comment by knro** [comment]
Any idea if you can submit a patch for this?

**Comment by k-ross** [comment]
I decided to take a stab at fixing this. Pull request created. :)
