### ISSUE TITLE
ZWO flip colors

### ISSUE THREAD

**Issue by luzik** [indilib/indi-3rdparty#400]
When I use flip option in ZWO camera, in color fits view there are some stripes on produced image. Is it possible that flip also reverse RGB pattern ?

Is there a better way to tell kstars that I use diagonal with my camera ? or maybe I do not have to do this and resolving will work anyway with flipped image and I should just use mirror button in fits viewer ?

**Comment by knro** [comment]
Interesting observation... I'm not sure if it is as simple as flipping the pattern, but why don't you try it out and report back? Put the pattern as BGGR in INDI and capture a flipped image, how does it look?
