### ISSUE TITLE
Libpigpiod conflicts with Libpigpio-dev

### ISSUE THREAD

**Issue by rkaczorek** [indilib/indi-3rdparty#415]
libpigpiod conflicts with libpigpio-dev (originaly provided by OS) due to it provides custom pigpiod.h which tries to overwrite original header file.

running sudo dpkg -i libpigpiod results in:
````
dpkg: error processing archive libpigpiod_0.2_armhf.deb (--install):
 trying to overwrite '/usr/include/pigpio.h', which is also in package libpigpio-dev 1.79-1+rpt1
````
What is a rationale behind providing custom libpigpio within INDI framework while it is provided by OS itself? I believe it is really bad practice.

**Comment by TallFurryMan** [comment]
Reference: https://github.com/indilib/indi-3rdparty/pull/329, there seems to be an issue with the debian package.
