### ISSUE TITLE
release plan of libtoupcam v1.49.1 on mutlaqja ppa

### ISSUE THREAD

**Issue by hangpark** [indilib/indi-3rdparty#416]
hi all!

can I know when it will be available to download libtoupcam 1.49.1 with apt mutlaqja ppa?

can't wait for testing my new camera with indi!

i'm new to here, and i'm even not sure that ppa releases are belong to this repo's scope.
but i think @knro can answer me.

thanks for your supports!

**Comment by knro** [comment]
@hangpark It's already in the Nightly PPA: https://code.launchpad.net/~mutlaqja/+recipe/libtoupcam-nightly

Once we release INDI v1.9.1 officially, it will also be in the stable PPA.

**Comment by hangpark** [comment]
@knro thanks a lot. but sadly, my ATR3CMOS26000KMA (risingcam IMX571 mono) failed to connect to indi.... :(
