### ISSUE TITLE
Version inconsitency between CMakeLists and lib

### ISSUE THREAD

**Issue by paolostivanin** [indilib/indi-3rdparty#422]
The CMakeLists report that the QHY so_version is `21`, but looking into the provided bin it seems to be `20`:

https://github.com/indilib/indi-3rdparty/blob/50ef09fbba63a702029ad00511487922d58d8a1f/libqhy/CMakeLists.txt#L6

```
$ strings Downloads/libqhyccd_x86_64.bin |grep libqhyccd
libqhyccd.so.20
```

This is the same for both `1.9.1` and latest master.

**Comment by knro** [comment]
I can confirm this issue, SONAME "20" is hardcoded to the CMakelists.txt. I asked QHY to fix this in their next release.

**Comment by knro** [comment]
SOVERSION reverted to 20 now.
