### ISSUE TITLE
Exposure timeouts with Toupcam USB2 cameras

### ISSUE THREAD

**Issue by bgilsrud** [indilib/indi-3rdparty#463]
I'm seeing exposure timeouts when autoguiding using a Meade LPI-GM camera. When the timeouts occur, it can take around 30s before a new exposure is requested. This extended delay will cause the guide accuracy to drop.

It would be nice if these timeouts could be avoided, but the next best thing would be to reduce the time it takes to recognize that the exposure isn't going to complete and start a new exposure.

**Comment by bgilsrud** [comment]
I'm happy to work on this since I can easily reproduce the issue.

**Comment by knro** [comment]
Sure go ahead, I've tried to deal with timeouts before as you can see in the code.

**Comment by knro** [comment]
@bgilsrud I don't recall if this was already fixed or not?

**Comment by wlatanowicz** [comment]
`m_DownloadEstimation` can become negative. This PR fixes the issue: https://github.com/indilib/indi-3rdparty/pull/576
