### ISSUE TITLE
indi_qhy_ccd searches for wrong qhy sdk

### ISSUE THREAD

**Issue by RononDex** [indilib/indi-3rdparty#473]
**Describe the bug**
Since the recent update, indi_qhy_ccd keeps crashing with the following error message: 
![image](https://user-images.githubusercontent.com/2249071/137190953-b7c8d09b-caed-4360-8ae0-f23a9e4a3c29.png)

I already uninstalled and reinstalled everything, even built everything from source, problem still persists.

Following files exist:
![image](https://user-images.githubusercontent.com/2249071/137191091-c1eb4e17-f61d-41bf-9e09-f16733f212ec.png)

I then tried tricking it by making a symlink libqhyccd.so.20 pointing to libqhyccd.so.
This allowed the driver to start and connect to the camera, but it keeps crashing every few seconds and driver needs to restart.

**To Reproduce**
Exact steps to reproduce the behavior.
1. Run `indi_qhy_ccd`

**Expected behavior**
indi_qhy_ccd should work as expected, connect to the camera and not crash and use the installed sdk etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/2249071/137190871-2140d693-3cd3-450d-8b1c-74fbc863fb88.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux ARM (armv7l)

**Log Files**
Make sure to enable logging and include log files https://indilib.org/support/logs-submission.html

**Comment by xsnrg** [comment]
The version of the library was updated to 21, and it looks like your install has 21.9.10, so that is good. 
It looks like indi-qhy is still looking for 20 when it should be looking for 21. Make sure your sources are up to date, and try re-compiling indi-qhy.

**Comment by RononDex** [comment]
What exactly do you mean by `make sure sources are up to date`? I already tried deleting the local source folders, cloning them again (for indi, indi-3rdparty and kstars) and recompiling everything, still the issues persists.

Is it possible there is some file I have to delete locally?

**Comment by RononDex** [comment]
I was able to get it running now, however, the qhy driver now keeps crashing every few seconds.
Here is a logfile with ccd debug logging enabled
[logfile-ekos.txt](https://github.com/indilib/indi-3rdparty/files/7345805/logfile-ekos.txt)
:

**Comment by knro** [comment]
Ok it's no longer crashes but apparently there is USB error. Try changing cables/ports.
