### ISSUE TITLE
iOptron CEM70G iGuider/iPolar issue

### ISSUE THREAD

**Issue by dbadavekc** [indilib/indi-3rdparty#475]
When selecting the iGuider as the guider in KSTARSon a CEM70G, the actual hardware that's used by Indi is always iPolar.
On a whim, I tried swapping iGuider for iPolar as a device, but iPolar was always chosen.

Not sure how to manually configure it to use the correct device - any help is greatly appreciated!

<img width="782" alt="image" src="https://user-images.githubusercontent.com/27701673/138126358-131483bb-1ad2-4a12-ab5b-e52419422044.png">

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/27701673/138126022-a5403b49-b365-4e10-a28a-d7d0b6b6652c.png">

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/27701673/138126160-9fb32c3d-b81e-45b4-9d23-69e74cc7840e.png">

**Comment by knro** [comment]
In Options, you can change the port from /dev/video0 to /dev/video1 for example and so forth. I actually don't see this as a good solution, so I'm working with @rlancaste to come up with a way to connect directly to each device.

**Comment by knro** [comment]
The latest drivers should automatically detect both devices in INDI Core library.
