### ISSUE TITLE
[ERROR] Error starting exposure with Sony DSLR driver and Sony NEX-3N device

### ISSUE THREAD

**Issue by ccaramel** [indilib/indi-3rdparty#5]
I cannot make an exposure with Sony NEX-3N using Sony-dslr driver.
Got every time the same error: [ERROR] Error starting exposure

I tried using gphoto CCD driver and I got the same behavior.

I'm on Osx Mojave with latest Kstars release 3.3.4 (idem with 3.3.6) and its embedded INDI Library.
Tested using local INDI server.

I tested using a remote INDI server on RPI in order to test latest Nightly INDI Library and got exactly the same issue.

It worth mentioning that my Nex-3N is in bulb mode (Writed on its LCD screen).

Please find attached log file.
[log_16-51-22.txt](https://github.com/indilib/indi-3rdparty/files/3627414/log_16-51-22.txt)

Also tried to use gphoto directly:
gphoto2 --debug --debug-logfile=gphoto.txt --capture-image-and-download
with log file here: 
[gphoto2.txt](https://github.com/indilib/indi-3rdparty/files/3627417/gphoto2.txt)

I also posted the issue to gphoto/ligphoto2 GitHub:
https://github.com/gphoto/libgphoto2/issues/439

Regards,

Christian.

**Comment by lewcherwyn** [comment]
Hi,I think maybe the libgphoto driver maybe not support nex3n to capature.
I also have a nex3n ready for Astrophotography.
I can use the timer remote controller to control the exposure,but I can not through the indi platform.
If you have any solutions please let me to konw.
Thanks a lot.
