### ISSUE TITLE
indiduinometeo+SQM 

### ISSUE THREAD

**Issue by porkyhttp** [indilib/indi-3rdparty#51]
Hi all,
I want to know if the SQM reading done by indiduinometeoSQM has been calibrated against an official SQM device.

In the code is reported the formula for the SQM read in mag/arcsec2 
mag_arcsec2 = log10(lux/108000)/-0.4;
Where this info came from???

I build my indiduinometeoSQM, but SQM values are much different from a Unihedron SQM that use a TSL237 sensor

**Comment by sterne-jaeger** [comment]
The formula should be correct, at least it is the same as http://unihedron.com/projects/darksky/magconv.php
