### ISSUE TITLE
Use a pointer

### ISSUE THREAD

**Issue by algebrato** [indilib/indi-3rdparty#511]
Dear all,
I would like to discuss the line: https://github.com/indilib/indi-3rdparty/blob/7ad91f54161f6f04a66a4807f0ed2f6525a1b892/libqhy/qhyccd.h#L913 

The definition of the syscall `QHYCCD_fpga_list(struct fpga_info_list &list)` requires a reference to `fpga_info_list`. What do you think to change this line in `QHYCCD_fpga_list(struct fpga_info_list *list)` in order to dynamically allocate the list of the all fpga-s attached to you pc. 

Stefano.

**Comment by knro** [comment]
Hi, you can ask QHYCCD this as it is developed by them.

**Comment by algebrato** [comment]
Thank you for your reply! I can close this issue.
