### ISSUE TITLE
Opening remote serial shutter port: /dev/tty.usbserial-xxxx is blocked on Mac

### ISSUE THREAD

**Issue by captainchain** [indilib/indi-3rdparty#584]
**Describe the bug**
open remote serial shutter port blocked when I set a 40 seconds exposure on Ekos (set Force BULB ON on INDI Control Panel),
then it blocked forever except I restart the KSTARS

CPU:Intel Core i7
OS: MacOS Monterey 12.3.1 (21E258) 
KSTARS: Version 3.5.8 Stable
KDE Frameworks  Version 5.92.0
DSLR: Nikon D5100
USBtoTTL chip: FT232R, Driver: https://www.ftdichip.com/Drivers/VCP/MacOSX/FTDIUSBSerialDextInstaller_1_4_7.zip

**To Reproduce**
Exact steps to reproduce the behavior.
1. start kstars
2. click Toggle Ekos
3. click Start Button with Nikon D5100 profile on Ekos Panel
4. after INDI Control Panel shown, click Nikon DSLR TAB,  set my FT232R serial port No. on Shutter Release Port
5. click connect button to connect to the DSLR
6. click option tab on INDI Control Panel , set Force BULB to ON
7. back to Ekos Panel, click CCD Tab and then set exposures at 40 seconds 
8. click Capture button

Expected behavior**
the shutter opens，then close after 40 seconds 

**Screenshots**

**MacBookPro (please complete the following information):**
CPU:Intel Core i7
OS: MacOS Monterey 12.3.1 (21E258) 
KSTARS: Version 3.5.8 Stable
KDE Frameworks  Version 5.92.0
DSLR: Nikon D5100
USBtoTTL chip: FT232R, Driver: https://www.ftdichip.com/Drivers/VCP/MacOSX/FTDIUSBSerialDextInstaller_1_4_7.zip

**Log Files**
INFO	20.704069 sec	: Force BULB is enabled. All expsures shall be captured in BULB mode except for subsecond captures.
INFO	64.539492 sec	: Starting 40 seconds exposure.
DEBUG	64.539565 sec	: Starting exposure (exptime: 40 secs, mirror lock: 0, force bulb: true, exposure index: 1)
DEBUG	64.539613 sec	: Mutex locked
DEBUG	64.539681 sec	: Setting radio/menu widget iso: 0 (100)
DEBUG	64.540377 sec	: Setting new configuration OK.
DEBUG	64.540442 sec	: Setting radio/menu widget imagequality: 3 (NEF (Raw))
DEBUG	64.541012 sec	: Setting new configuration OK.
DEBUG	64.541064 sec	: Setting exposure widget bulb index: 52
DEBUG	64.541085 sec	: Setting radio/menu widget shutterspeed2: 52 (Bulb)
DEBUG	64.541832 sec	: Setting new configuration OK.
DEBUG	64.541882 sec	: Opening remote serial shutter port: /dev/tty.usbserial-xxxx ...

Finally I searched the source code at: 
https://github.com/indilib/indi-3rdparty/blob/a70b1529e8c4e68216454fa453e5d62b4da85b0b/indi-gphoto/gphoto_driver.cpp#L1063

I did a test via CLion, then found that:
open() can not be written like : open(gphoto->bulb_port, O_RDWR, O_NONBLOCK);
must be written as: open(gphoto->bulb_port, O_RDONLY  | O_NONBLOCK);

**Comment by knro** [comment]
oh I see that O_NONBLOCK was sent as the mode_t which is incorrect. Does O_RDWR | O_NONBLOCK work as well ?

**Comment by captainchain** [comment]
@knro pretty well
