### ISSUE TITLE
INDI QHY firmware not installing in /usr/lib/firmware/qhy

### ISSUE THREAD

**Issue by sonny486** [indilib/indi-3rdparty#602]
installing the indi-qhy package, the firmware for QHY ends up in /usr/lib/firmware not /usr/lib/firmware/qhy.

New builds fail due to qhy firmware not located.  fxload fails.

**Comment by knro** [comment]
indi-qhy does not install any firmware, it's installed by libqhy package and that installs it to 

`/lib/firmware/qhy` and it has not changed in many years.
