### ISSUE TITLE
indi_sv305_ccd: Native file format can be selected, but the driver does not support Native.

### ISSUE THREAD

**Issue by jctk** [indilib/indi-3rdparty#665]
**Describe the bug**
"Native" format can be selected in the Ekos camera module.
When Native format is selected and a picture is taken, the camera terminates abnormally the second time.

**To Reproduce**
1. Select Native format in the Ekos camera module.
2. Capture a shot with the "Capture a perview" button.
3. Fits viewer is not displayed.
4. Capture a shot with the "Capture a perview" button again.
5. indi_sv305_ccd and KStars terminates abnormally.

**Expected behavior**
"Native" format does not appear as an option. Or, it is possible to shoot in "Native" format.

**Screenshots**
![image](https://user-images.githubusercontent.com/52247294/193028401-540f6756-b8f2-47a7-b115-fbaffc0cb602.png)

**Desktop (please complete the following information):**
 - OS: INDI Server work on Raspberry PI 4B Stellarmate OS
 - OS: KStars works on Windows 11.
 - INDI Version 1.9.7 and 1.9.8

**Log Files**
[log_21-16-22.txt](https://github.com/indilib/indi-3rdparty/files/9674561/log_21-16-22.txt)

**Comment by jctk** [comment]
This issue was reproduced in indi_asi_ccd as well.

Is following issue the same ?
https://www.indilib.org/forum/ccds-dslrs/3293-kstars-2-9-4-crashing-when-previewing-with-native-format/25153.html

**Comment by jctk** [comment]
Hi, @knro 

I don't know what 'Native' format is.
Is the data output by the Camera driver directly into a file ?

**Comment by knro** [comment]
Yes it's how you encode the data. Native means whatever the driver deems. For some DSLR cameras, it captures in JPG and you can **encode** it as either FITS or *native* JPG and send as-is. For ASI and SV cameras, there is no native, native would be just raw data which cannot be read. 

We should probably add a method to remove "Native" from the available selections for some drivers.

**Comment by knro** [comment]
A simple trick now that might EncodeFormatSP.nsp = 1 in UpdateProperties()

**Comment by jctk** [comment]
> We should probably add a method to remove "Native" from the available selections for some drivers.

Yes, I agree with you.

> A simple trick now that might EncodeFormatSP.nsp = 1 in UpdateProperties()

I will try sonn it.
Thanks !
