### ISSUE TITLE
indi-toupbase driver: Add control for new "high full well mode" with touptek SDK v53

### ISSUE THREAD

**Issue by 42-max** [indilib/indi-3rdparty#699]
In the Indi Forum user LANCO announced a new SDK Version for the Touptek cameras. The new version offers a new high full well option. This option should be included as a control in thre INDI driver.

My proposal is to include "Enable" and "Disable" buttons into the Control Tab just below the "Low Noise Mode" option.

If nobody has started the implementation yet I will start soon...   Please let me know if you have further infomation about this mode or any comments.

CS Max

**Comment by knro** [comment]
It appears you have a PR in progress? Please submit when ready, it would be greatly appreciated!

**Comment by knro** [comment]
@touptek is this planned for the driver?

**Comment by knro** [comment]
IIRC this is already merged? Please re-open if not the case.
