### ISSUE TITLE
Save CCD temperature, cooler status and heater in config XML

### ISSUE THREAD

**Issue by teoteo** [indilib/indi-3rdparty#725]
**Is your feature request related to a problem? Please describe.**
I usually shot with *desired temperature at -10°C* with *cooler* and *anti dew heater* on. 
Sometimes I forget to set it before a session and I get subframes with cooler disabled.

**Describe the solution you'd like**
Save in CCD *_config.xml file the temperature, cooler and heater status, and use them to set the camera in this status once connected.

**Comment by knro** [comment]
I don't think driver should make this decision, why don't you client set it to these settings when capturing?
