### ISSUE TITLE
Wrong Driver name Star Adventurer GTi

### ISSUE THREAD

**Issue by jctk** [indilib/indi-3rdparty#728]
**Describe the bug**
Sky-watcher "Star Adventurer GTi" is now "SkyAdventurer GTi".

**To Reproduce**
Exact steps to reproduce the behavior.
1. Edit profile
2. Show dropdown list for mount
3. There you will find the "SkyAdventurer GTi."

**Expected behavior**
There are "Star Adventurer GTi" in dropdown list for mount.

**Screenshots**
![image](https://user-images.githubusercontent.com/52247294/218735802-2d4f86ed-eacb-4299-93fe-a4b2fc66b003.png)

**Desktop (please complete the following information):**
 - OS: Stellarmate OS and Windows
 - INDI 2.0, KStars 3.6.3

**Comment by knro** [comment]
Fixed in INDI 2.0.6
