### ISSUE TITLE
incorrect glibc for libqhy

### ISSUE THREAD

**Issue by rsarwar87** [indilib/indi-3rdparty#762]
Hi
I was upgrading my repos from 1.9.7 to 2.0.0. it seems the libqhy binaries were updated since but those binaries were built against glibc 2.34, potentially targeting bullseye. is there a bullseye version of astroberry that i am not aware of? Otherwise, we might want to revert back those bins

**Comment by knro** [comment]
This is a downstream issue. Yes it was built against bullseye, you might want to check with your distribution support.
