### ISSUE TITLE
QHY INDI Driver no longer shows Cooling function - QHY600M

### ISSUE THREAD

**Issue by sonny486** [indilib/indi-3rdparty#766]
QHY INDI Driver panel no longer shows the cooling function.

Start QHY INDI DRIVER

**Expected behavior**
Cooling function should be listed and available for K-Starts to command

**Screenshots**
![image](https://user-images.githubusercontent.com/43073912/227752415-e3dbea4a-27be-4628-baa2-812552aea6fb.png)

**Desktop (please complete the following information):**
 - OS: Desktop Windows 11 - K-Stars build 2023-03-25T08:21:49Z
- OS: INDI-SERVER - Ubuntu x64 22.04 - Built INDI from GIT 26 - 3 - 2023 Latest versions of both INDI and INDI3rdParty
- 

**Log Files**
Make sure to enable logging and include log files https://indilib.org/support/logs-submission.html

**Comment by knro** [comment]
Can you reproduce this with INDI 3rdparty 2.0.2 release a couple of days ago?
