### ISSUE TITLE
Problem with Astroberry and Player One Ares-C Pro

### ISSUE THREAD

**Issue by juanmamores** [indilib/indi-3rdparty#859]
Good morning. I have been using Astroberry for several months with an EQM35, a TS Optics refractor, a Canon camera and a Player One Neptune CII as guide camera. Everything has worked correctly. Today I received my Player One Ares-C Pro to replace the Canon. I have updated the configuration in Kstars/Ekos but I cannot connect the Ares-C Pro. The Neptune CII still connects well. Has anyone had this same problem? Could it be a problem with the indi drivers?
Sorry if this is not the right place to ask this.
Thanks

**Comment by hiro3110i** [comment]
@juanmamores Thank you for your report.
For Ares and Saturn series using IMX533 sensors on arm linux system,
you may want to roll back indi playerone camera driver to v1.10.
Previous drivers may lack some supported functions, but overall operation seems to be stable.
Manufacturer engineers are continuing to analyze this issue.
I hope this will be resolved with an SDK update.

**Comment by juanmamores** [comment]
Thank you very much Hiroshi for your reply.
Greetings

**Comment by PlayerOneAstronomy** [comment]
@juanmamores The indilib version in your astroberry is a bit low. Lei said that he has upgraded indilib for you. If your Ares is working properly, please close this issue, thanks.

**Comment by juanmamores** [comment]
Good morning. Now everything works correctly. The Ares-C Pro camera is recognized in Ekos and all thanks to Lei who kindly helped me solve the problem. Today he connected to my computer remotely and updated the version of indilib. Very grateful to PlaerOne and especially to Lei.
Greetings and clear skies!
