### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by nikodemusP** [indilib/indi-3rdparty#876]
**Describe the bug**
There are several build-issues within the CMakefiles 

* cmake_minimum_required should be upgraded at least 3.5 or higher => avoid of Warnings
* exec_program is deprecated => should be changed to execute_process

i.e.

CMake Warning (dev) at indi-gphoto/make_gphoto_symlink.cmake:1 (exec_program):
  Policy CMP0153 is not set: The exec_program command should not be called.
  Run "cmake --help-policy CMP0153" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Use execute_process() instead.
Call Stack (most recent call first):
  indi-gphoto/cmake_install.cmake:86 (include)
  cmake_install.cmake:48 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

* TOUPBASE requires libmeadecam, but is not build within the "lib"

--- a/CMakeLists.txt	2023-12-25 16:48:59.734605816 +0100
+++ b/CMakeLists.txt	2023-12-25 17:03:34.432832655 +0100
@@ -357,6 +357,7 @@
 add_subdirectory(libmallincam)
 add_subdirectory(libomegonprocam)
 add_subdirectory(libtscam)
+add_subdirectory(libmeadecam)
 endif (WITH_TOUPBASE)

**To Reproduce**
a) Build the libraries with CMake 3.28
b) Build the driver

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch-Linux
 - Version 6.6
 - CMake 3.28

**Log Files**

**Comment by knro** [comment]
This is resolved in master, please try again.
