### ISSUE TITLE
Touptek camera resolution issue on RPi

### ISSUE THREAD

**Issue by vladtcvs** [indilib/indi-3rdparty#878]
**Describe the bug**
When I use my Omegon Vetec Pro 16000M camera on PC (amd64), I see full resolution 4640x3506. But when I use it on RPi (armhf), I see resolution 1536x1160. 

**To Reproduce**
Exact steps to reproduce the behavior.
1. Connect camera to RPi
2. Run driver (omegon or toupcam)
3. See low resolution on RPi

**Expected behavior**
Full resolution on RPi

**Screenshots**
PC: 
![image](https://github.com/indilib/indi-3rdparty/assets/3390973/8e9d353b-c8fe-49f9-948d-acea1e4ac264)

RPi (remote connection):
![image](https://github.com/indilib/indi-3rdparty/assets/3390973/37bbbbc6-4bba-465f-a98d-a2e43597f72c)

**Desktop (please complete the following information):**
 - OS: Debian on PC and Raspbian on RPi
 - Version: PPA version 2.1+t202311131302~ubuntu23.04.1 on PC
                   [4ddc7a0](https://github.com/indilib/indi-3rdparty/commit/4ddc7a01881948fd4f1a33f03baf14184cbd449c) on RPi

**Comment by vladtcvs** [comment]
I've tested `demosimplest` sample from Omegon SDK, both on PC and RPi, and for bot cases I see `4640x3506` resolution:
```
event callback: 0x0001
...
press ENTER to exit
event callback: 0x0001
pull image ok, total = 1, res = 4640 x 3506
```

**Comment by vladtcvs** [comment]
Sorry, after some searching inside configs I've founded that it was config for use low resolution

**Comment by knro** [comment]
I made this change on purpose because capture on high resolution was failing by default on armhf. You can still change resolution but it just defaults to low-res.
