### ISSUE TITLE
Player One Saturn-C times out every second capture attempt.

### ISSUE THREAD

**Issue by glundby** [indilib/indi-3rdparty#891]
**Describe the bug**
Camera Player One Saturn-C (IMX533)
indi_playerone_ccd     version 1.12   interface 6    sdk 3.6.0  
Times out every second capture attempt after a few minutes. Next capture proceeds normal with download, next hangs after count down to zero and times out after several minutes and so on.

**To Reproduce**
Make sequence of 10 subs a 10s (1s does not reveal the problem!)
Start sequence and observe every second sub to timeout

**Expected behavior**
Rolling back to indi_playerone_ccd    version 1.0   interface 6   SDK 3.1.1.0 
The camera behaves as expected and captures any sequence without any problems!

**Screenshots**

**Desktop (please complete the following information):**
 - OS: StellarMate 1.8.0
 - Version Kstars 3.6.8 Stable

**Log Files**
Make sure to enable logging and include log files https://indilib.org/support/logs-submission.html

**Comment by glundby** [comment]
I upgraded to RPi5 to see if the better HW might solve the problem, but no!

**Comment by hiro3110i** [comment]
@glundby Thank you for reporting the issue.
Now I have Saturn-C in my hand, and I tested it with the latest indi_playerone_ccd v1.13 (SDK v3.6.1).
It is working with no problem in my environment (Ubuntu Mate 20.04 on RasPi4/4GB).
Could you please contact to PlayerOne Support? They will have a solution for individual Saturn-C.

By the way, RasPi5 cannot tested at this moment because I cannot buy it in Japan now due to legal issue of wifi radio.
I'll test RasPi5 as soon as possible if I'll be able to buy it here.

**Comment by glundby** [comment]
Interesting!

How can I update one step to v1.13 and SDK to 3.6.1?
I would like to try it.

As for RPi5, It runs everything but much faster.  I'm even able to run FireCapture with the PO Saturn on it.

Regards! Gustav Lundby
________________________________
Fra: Hiroshi SAITO ***@***.***>
Sendt: tirsdag 30. januar 2024 13:52
Til: indilib/indi-3rdparty ***@***.***>
Kopi: Gustav Olav Lundby ***@***.***>; Mention ***@***.***>
Emne: Re: [indilib/indi-3rdparty] Player One Saturn-C times out every second capture attempt. (Issue #891)


@glundby<https://github.com/glundby> Thank you for reporting the issue.
Now I have Saturn-C in my hand, and I tested it with the latest indi_playerone_ccd v1.13 (SDK v3.6.1).
It is working with no problem in my environment (Ubuntu Mate 20.04 on RasPi4/4GB).
Could you please contact to PlayerOne Support? They will have a solution for individual Saturn-C.

By the way, RasPi5 cannot tested at this moment because I cannot buy it in Japan now due to legal issue of wifi radio.
I'll test RasPi5 as soon as possible if I'll be able to buy it here.

**Comment by hiro3110i** [comment]
@glundby At first, you should contact to PlayerOne support to update the firmware.
It will be the most important thing to solve the Saturn-C issue.

Current distributed version is v1.12 which is included in KStars v3.6.1.
You have to build it from source code if you want to use v1.13 now.

**Comment by glundby** [comment]
Hello!

Thank you! version 1.13 of the driver works! Problem solved!

Regards!

Gustav Olav Lundby
________________________________
Fra: Hiroshi SAITO ***@***.***>
Sendt: onsdag 31. januar 2024 14:12
Til: indilib/indi-3rdparty ***@***.***>
Kopi: Gustav Olav Lundby ***@***.***>; Mention ***@***.***>
Emne: Re: [indilib/indi-3rdparty] Player One Saturn-C times out every second capture attempt. (Issue #891)


@glundby<https://github.com/glundby> At first, you should contact to PlayerOne support to update the firmware.
It will be the most important thing to solve the Saturn-C issue.

Current distributed version is v1.12 which is included in KStars v3.6.1.
You have to build it from source code if you want to use v1.13 now.

**Comment by hiro3110i** [comment]
@glundby I'm glad to hear the words "SOLVED"!
Thanks again for your contribution.
Could you please close this thread?

**Comment by hiro3110i** [comment]
@knro This issue was solved by firmware update.
Could you please close this issue?
