### ISSUE TITLE
libgmock-dev is missing...

### ISSUE THREAD

**Issue by kris969** [indilib/indi-3rdparty#911]
**Describe the bug**
In the git documentation, it should be useful to add the "libgmock-dev" in the list of libraries to install.

**Comment by knro** [comment]
Really? I never thought it was a must. We can add it sure.

**Comment by kris969** [comment]
I am using a raspi 4 running a fresh bookworm PI OS.
After having download sources from git, and following the installation
process as describe, this library was required.
That's the context.

Le dimanche 07 avril 2024 à 02:22 -0700, Jasem Mutlaq a écrit :
