### ISSUE TITLE
qhy_ccd streaming/record saves .ser files in grayscale for color camera

### ISSUE THREAD

**Issue by klarrieu** [indilib/indi-3rdparty#974]
**Describe the bug**
Issue with indi_qhy_ccd driver:

Using QHYCCD 5III462C camera. I am able to see color images in the stream, and running `qhy_ccd_test` indicates it identifies the camera as a color camera. However, when trying to record and save to SER files (RAW encoder), they are saved in grayscale.

**To Reproduce**
1. Start streaming.
2. Make a recording.
3. Saved .ser file is grayscale. No errors are raised.

**Expected behavior**
The saved .ser files should have color and bayer information.

**Desktop:**
 - OS: astroberry 2.0.5 (Rpi 4)
 - general info on Kstars indi control panel says SDK version 22.7.8

**Comment by knro** [comment]
This is a very old version of INDI. Please update and re-test.
