### ISSUE TITLE
gphoto fails to compile

### ISSUE THREAD

**Issue by apalazzi** [indilib/indi-3rdparty#977]
**Describe the bug**
I was going to test the claim that the bug #976 was indeed fixed, so I pulled the latest sources and tried to compile, however it fails.

**To Reproduce**
1. git pull the latest sources
2. mkdir -p ~/Projects/build/indi-gphoto
3. cd ~/Projects/build/indi-gphoto
4. cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug ~/Projects/indi-3rdparty/indi-gphoto
5. make -j4

**Expected behavior**
The driver sould build successfully

**Desktop (please complete the following information):**
 - OS: Debian trixie/sid
 - Version: git

**Log Files**
See attachment.
[make.log](https://github.com/user-attachments/files/17058537/make.log)

**Comment by knro** [comment]
You need to rebuild and install indi first.
