### ISSUE TITLE
Indilib indi-3rd party indi-qhy fails to make

### ISSUE THREAD

**Issue by zacn** [indilib/indi-3rdparty#985]
**Describe the bug**
Following the procedure given in README.md to build indi-qhy. I had previously installed indi-core. Installed indilib OK. Cmake for indi-qhy worked OK but then make failed. Error messages as shown below.

***** Please note. I have had a similar problem with indi-eqmod - see issue #981. This was on the same system *****

zac@rpi1:~/Projects/build/indi-qhy $ mkdir test
zac@rpi1:~/Projects/build/indi-qhy $ cd test
zac@rpi1:~/Projects/build/indi-qhy/test $ cmake -DCMAKE_INSTALL_PREFIX=/usr ~/Projects/indi-3rdparty/indi-qhy
-- The CXX compiler identification is GNU 12.2.0
-- The C compiler identification is GNU 12.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found CFITSIO 4.2.0: /usr/lib/aarch64-linux-gnu/libcfitsio.so
-- Found INDI: /usr/lib/aarch64-linux-gnu/libindidriver.so;/usr/lib/aarch64-linux-gnu/libindiAlignmentDriver.so (found version "1.9.9") 
-- Found QHY: /usr/lib/aarch64-linux-gnu/libqhyccd.so
-- Found ZLIB: /usr/lib/aarch64-linux-gnu/libz.so (found version "1.2.13") 
-- Found NOVA: /usr/lib/aarch64-linux-gnu/libnova.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.1") 
-- Found USB1: /usr/lib/aarch64-linux-gnu/libusb-1.0.so (found version "1.0.26") 
-- Performing Test USB1_HAS_LIBUSB_ERROR_NAME
-- Performing Test USB1_HAS_LIBUSB_ERROR_NAME - Success
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Using indi bundled json library
-- Performing Test COMPATIBLE_FORTIFY_SOURCE
-- Performing Test COMPATIBLE_FORTIFY_SOURCE - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zac/Projects/build/indi-qhy/test
zac@rpi1:~/Projects/build/indi-qhy/test $ make
[ 12%] Building CXX object CMakeFiles/indi_qhy_ccd.dir/qhy_ccd.cpp.o
In file included from /home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:23:
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.h:91:75: error: ‘FITSRecord’ is not a member of ‘INDI’
   91 |         void addFITSKeywords(INDI::CCDChip *targetChip, std::vector<INDI::FITSRecord> &fitsKeywords) override;
      |                                                                           ^~~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.h:91:75: error: ‘FITSRecord’ is not a member of ‘INDI’
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.h:91:85: error: template argument 1 is invalid
   91 |         void addFITSKeywords(INDI::CCDChip *targetChip, std::vector<INDI::FITSRecord> &fitsKeywords) override;
      |                                                                                     ^
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.h:91:85: error: template argument 2 is invalid
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.h:91:14: error: ‘void QHYCCD::addFITSKeywords(INDI::CCDChip*, int&)’ marked ‘override’, but does not override
   91 |         void addFITSKeywords(INDI::CCDChip *targetChip, std::vector<INDI::FITSRecord> &fitsKeywords) override;
      |              ^~~~~~~~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp: In member function ‘virtual bool QHYCCD::Connect()’:
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:1034:24: error: no match for ‘operator[]’ (operand types are ‘ITextVectorProperty’ {aka ‘_ITextVectorProperty’} and ‘int’)
 1034 |                 BayerTP[2].setText("GBRG");
      |                        ^
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:1039:24: error: no match for ‘operator[]’ (operand types are ‘ITextVectorProperty’ {aka ‘_ITextVectorProperty’} and ‘int’)
 1039 |                 BayerTP[2].setText("GRBG");
      |                        ^
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:1044:24: error: no match for ‘operator[]’ (operand types are ‘ITextVectorProperty’ {aka ‘_ITextVectorProperty’} and ‘int’)
 1044 |                 BayerTP[2].setText("BGGR");
      |                        ^
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:1049:24: error: no match for ‘operator[]’ (operand types are ‘ITextVectorProperty’ {aka ‘_ITextVectorProperty’} and ‘int’)
 1049 |                 BayerTP[2].setText("RGGB");
      |                        ^
In file included from /usr/include/libindi/defaultdevice.h:23,
                 from /usr/include/libindi/indiccd.h:30,
                 from /home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.h:25:
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:1053:51: error: no match for ‘operator[]’ (operand types are ‘ITextVectorProperty’ {aka ‘_ITextVectorProperty’} and ‘int’)
 1053 |             LOGF_DEBUG("Color camera: %s", BayerTP[2].getText());
      |                                                   ^
/usr/include/libindi/indilogger.h:58:91: note: in definition of macro ‘DEBUGF’
   58 |     INDI::Logger::getInstance().print(getDeviceName(), priority, __FILE__, __LINE__, msg, __VA_ARGS__)
      |                                                                                           ^~~~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:1053:13: note: in expansion of macro ‘LOGF_DEBUG’
 1053 |             LOGF_DEBUG("Color camera: %s", BayerTP[2].getText());
      |             ^~~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp: In member function ‘virtual int QHYCCD::SetTemperature(double)’:
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:1267:41: error: no match for ‘operator[]’ (operand types are ‘INumberVectorProperty’ {aka ‘_INumberVectorProperty’} and ‘int’)
 1267 |     if (fabs(temperature - TemperatureNP[0].getValue()) < UPDATE_THRESHOLD)
      |                                         ^
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:1270:102: error: no match for ‘operator[]’ (operand types are ‘INumberVectorProperty’ {aka ‘_INumberVectorProperty’} and ‘int’)
 1270 |     LOGF_DEBUG("Requested temperature is %.f, current temperature is %.f", temperature, TemperatureNP[0].getValue());
      |                                                                                                      ^
/usr/include/libindi/indilogger.h:58:91: note: in definition of macro ‘DEBUGF’
   58 |     INDI::Logger::getInstance().print(getDeviceName(), priority, __FILE__, __LINE__, msg, __VA_ARGS__)
      |                                                                                           ^~~~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:1270:5: note: in expansion of macro ‘LOGF_DEBUG’
 1270 |     LOGF_DEBUG("Requested temperature is %.f, current temperature is %.f", temperature, TemperatureNP[0].getValue());
      |     ^~~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:1277:59: error: no match for ‘operator[]’ (operand types are ‘INumberVectorProperty’ {aka ‘_INumberVectorProperty’} and ‘int’)
 1277 |     setCoolerEnabled(m_TemperatureRequest <= TemperatureNP[0].getValue());
      |                                                           ^
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp: In member function ‘virtual bool QHYCCD::ISNewSwitch(const char*, const char*, ISState*, char**, int)’:
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:1682:61: error: no match for ‘operator[]’ (operand types are ‘INumberVectorProperty’ {aka ‘_INumberVectorProperty’} and ‘int’)
 1682 |                     double targetTemperature = TemperatureNP[0].getValue();
      |                                                             ^
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:1687:39: error: ‘INumberVectorProperty’ {aka ‘struct _INumberVectorProperty’} has no member named ‘setState’
 1687 |                         TemperatureNP.setState(IPS_BUSY);
      |                                       ^~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:1688:39: error: ‘INumberVectorProperty’ {aka ‘struct _INumberVectorProperty’} has no member named ‘apply’
 1688 |                         TemperatureNP.apply();
      |                                       ^~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:1713:35: error: ‘INumberVectorProperty’ {aka ‘struct _INumberVectorProperty’} has no member named ‘setState’
 1713 |                     TemperatureNP.setState(IPS_IDLE);
      |                                   ^~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:1714:35: error: ‘INumberVectorProperty’ {aka ‘struct _INumberVectorProperty’} has no member named ‘apply’
 1714 |                     TemperatureNP.apply();
      |                                   ^~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:1724:39: error: ‘INumberVectorProperty’ {aka ‘struct _INumberVectorProperty’} has no member named ‘setState’
 1724 |                         TemperatureNP.setState(IPS_IDLE);
      |                                       ^~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:1725:39: error: ‘INumberVectorProperty’ {aka ‘struct _INumberVectorProperty’} has no member named ‘apply’
 1725 |                         TemperatureNP.apply();
      |                                       ^~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp: In member function ‘void QHYCCD::updateTemperature()’:
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2239:43: error: no match for ‘operator[]’ (operand types are ‘INumberVectorProperty’ {aka ‘_INumberVectorProperty’} and ‘int’)
 2239 |         currentTemperature = TemperatureNP[0].getValue();
      |                                           ^
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2240:26: error: no match for ‘operator[]’ (operand types are ‘INumberVectorProperty’ {aka ‘_INumberVectorProperty’} and ‘int’)
 2240 |         if (TemperatureNP[0].getValue() < m_TemperatureRequest)
      |                          ^
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2242:31: error: no match for ‘operator[]’ (operand types are ‘INumberVectorProperty’ {aka ‘_INumberVectorProperty’} and ‘int’)
 2242 |         else if (TemperatureNP[0].getValue() > m_TemperatureRequest)
      |                               ^
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2253:27: error: ‘INumberVectorProperty’ {aka ‘struct _INumberVectorProperty’} has no member named ‘getState’
 2253 |         if (TemperatureNP.getState() == IPS_BUSY)
      |                           ^~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2263:74: error: ‘INumberVectorProperty’ {aka ‘struct _INumberVectorProperty’} has no member named ‘getState’
 2263 |         else if (CoolerModeS[COOLER_MANUAL].s == ISS_ON && TemperatureNP.getState() == IPS_OK)
      |                                                                          ^~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2273:52: error: no match for ‘operator[]’ (operand types are ‘INumberVectorProperty’ {aka ‘_INumberVectorProperty’} and ‘int’)
 2273 |     if (std::abs(currentTemperature - TemperatureNP[0].getValue()) > UPDATE_THRESHOLD)
      |                                                    ^
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2276:27: error: ‘INumberVectorProperty’ {aka ‘struct _INumberVectorProperty’} has no member named ‘setState’
 2276 |             TemperatureNP.setState(IPS_ALERT);
      |                           ^~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2278:26: error: no match for ‘operator[]’ (operand types are ‘INumberVectorProperty’ {aka ‘_INumberVectorProperty’} and ‘int’)
 2278 |             TemperatureNP[0].setValue(currentTemperature);
      |                          ^
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2279:23: error: ‘INumberVectorProperty’ {aka ‘struct _INumberVectorProperty’} has no member named ‘apply’
 2279 |         TemperatureNP.apply();
      |                       ^~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2284:28: error: ‘INumberVectorProperty’ {aka ‘struct _INumberVectorProperty’} has no member named ‘getState’
 2284 |     else if (TemperatureNP.getState() == IPS_OK && fabs(TemperatureNP[0].getValue() - m_TemperatureRequest) > UPDATE_THRESHOLD)
      |                            ^~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2284:70: error: no match for ‘operator[]’ (operand types are ‘INumberVectorProperty’ {aka ‘_INumberVectorProperty’} and ‘int’)
 2284 |     else if (TemperatureNP.getState() == IPS_OK && fabs(TemperatureNP[0].getValue() - m_TemperatureRequest) > UPDATE_THRESHOLD)
      |                                                                      ^
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2287:27: error: ‘INumberVectorProperty’ {aka ‘struct _INumberVectorProperty’} has no member named ‘setState’
 2287 |             TemperatureNP.setState(IPS_ALERT);
      |                           ^~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2290:26: error: no match for ‘operator[]’ (operand types are ‘INumberVectorProperty’ {aka ‘_INumberVectorProperty’} and ‘int’)
 2290 |             TemperatureNP[0].setValue(currentTemperature);
      |                          ^
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2291:27: error: ‘INumberVectorProperty’ {aka ‘struct _INumberVectorProperty’} has no member named ‘setState’
 2291 |             TemperatureNP.setState(IPS_BUSY);
      |                           ^~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2293:23: error: ‘INumberVectorProperty’ {aka ‘struct _INumberVectorProperty’} has no member named ‘apply’
 2293 |         TemperatureNP.apply();
      |                       ^~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp: In member function ‘virtual bool QHYCCD::StartStreaming()’:
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2451:16: error: no match for ‘operator[]’ (operand types are ‘ITextVectorProperty’ {aka ‘_ITextVectorProperty’} and ‘int’)
 2451 |     if (BayerTP[2].getText() && formats.count(BayerTP[2].getText()) != 0)
      |                ^
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2451:54: error: no match for ‘operator[]’ (operand types are ‘ITextVectorProperty’ {aka ‘_ITextVectorProperty’} and ‘int’)
 2451 |     if (BayerTP[2].getText() && formats.count(BayerTP[2].getText()) != 0)
      |                                                      ^
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2452:39: error: no match for ‘operator[]’ (operand types are ‘ITextVectorProperty’ {aka ‘_ITextVectorProperty’} and ‘int’)
 2452 |         qhyFormat = formats.at(BayerTP[2].getText());
      |                                       ^
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp: In member function ‘void QHYCCD::streamVideo()’:
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2611:31: error: no matching function for call to ‘INDI::StreamManager::newFrame(uint8_t*&, uint32_t, uint64_t&)’
 2611 |             Streamer->newFrame(buffer, w * h * bpp / 8 * channels, timestamp);
      |             ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/libindi/indiccd.h:37:
/usr/include/libindi/stream/streammanager.h:118:14: note: candidate: ‘void INDI::StreamManager::newFrame(const uint8_t*, uint32_t)’
  118 |         void newFrame(const uint8_t *buffer, uint32_t nbytes);
      |              ^~~~~~~~
/usr/include/libindi/stream/streammanager.h:118:14: note:   candidate expects 2 arguments, 3 provided
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp: At global scope:
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2740:75: error: ‘FITSRecord’ is not a member of ‘INDI’
 2740 | void QHYCCD::addFITSKeywords(INDI::CCDChip *targetChip, std::vector<INDI::FITSRecord> &fitsKeywords)
      |                                                                           ^~~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2740:75: error: ‘FITSRecord’ is not a member of ‘INDI’
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2740:85: error: template argument 1 is invalid
 2740 | void QHYCCD::addFITSKeywords(INDI::CCDChip *targetChip, std::vector<INDI::FITSRecord> &fitsKeywords)
      |                                                                                     ^
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2740:85: error: template argument 2 is invalid
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp: In member function ‘void QHYCCD::addFITSKeywords(INDI::CCDChip*, int&)’:
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2742:31: error: no matching function for call to ‘QHYCCD::addFITSKeywords(INDI::CCDChip*&, int&)’
 2742 |     INDI::CCD::addFITSKeywords(targetChip, fitsKeywords);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/libindi/indiccd.h:508:22: note: candidate: ‘virtual void INDI::CCD::addFITSKeywords(INDI::CCDChip*)’
  508 |         virtual void addFITSKeywords(CCDChip * targetChip);
      |                      ^~~~~~~~~~~~~~~
/usr/include/libindi/indiccd.h:508:22: note:   candidate expects 1 argument, 2 provided
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2746:22: error: request for member ‘push_back’ in ‘fitsKeywords’, which is of non-class type ‘int’
 2746 |         fitsKeywords.push_back({"GAIN", GainN[0].value, 3, "Gain"});
      |                      ^~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2751:22: error: request for member ‘push_back’ in ‘fitsKeywords’, which is of non-class type ‘int’
 2751 |         fitsKeywords.push_back({"OFFSET", OffsetN[0].value, 3, "Offset"});
      |                      ^~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2756:22: error: request for member ‘push_back’ in ‘fitsKeywords’, which is of non-class type ‘int’
 2756 |         fitsKeywords.push_back({"AMPGLOW", IUFindOnSwitch(&AMPGlowSP)->label, "Mode"});
      |                      ^~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2761:22: error: request for member ‘push_back’ in ‘fitsKeywords’, which is of non-class type ‘int’
 2761 |         fitsKeywords.push_back({"READMODE", ReadModeN[0].value, 1, "Read Mode"});
      |                      ^~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2768:22: error: request for member ‘push_back’ in ‘fitsKeywords’, which is of non-class type ‘int’
 2768 |         fitsKeywords.push_back({"GPS_SFLG", GPSHeader.start_flag, "StartFlag"});
      |                      ^~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2770:22: error: request for member ‘push_back’ in ‘fitsKeywords’, which is of non-class type ‘int’
 2770 |         fitsKeywords.push_back({"GPS_SS", GPSHeader.start_sec, "StartShutterSeconds"});
      |                      ^~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2772:22: error: request for member ‘push_back’ in ‘fitsKeywords’, which is of non-class type ‘int’
 2772 |         fitsKeywords.push_back({"GPS_SU", GPSHeader.start_us, 3, "StartShutterMicroSeconds"});
      |                      ^~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2774:22: error: request for member ‘push_back’ in ‘fitsKeywords’, which is of non-class type ‘int’
 2774 |         fitsKeywords.push_back({"GPS_ST", GPSDataStartT[GPS_DATA_START_TS].text, "StartShutterTime"});
      |                      ^~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2778:22: error: request for member ‘push_back’ in ‘fitsKeywords’, which is of non-class type ‘int’
 2778 |         fitsKeywords.push_back({"GPS_EFLG", GPSHeader.end_flag, "EndFlag"});
      |                      ^~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2780:22: error: request for member ‘push_back’ in ‘fitsKeywords’, which is of non-class type ‘int’
 2780 |         fitsKeywords.push_back({"GPS_ES", GPSHeader.end_sec, "EndShutterSeconds"});
      |                      ^~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2782:22: error: request for member ‘push_back’ in ‘fitsKeywords’, which is of non-class type ‘int’
 2782 |         fitsKeywords.push_back({"GPS_EU", GPSHeader.end_us, 3, "EndShutterMicroSeconds"});
      |                      ^~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2784:22: error: request for member ‘push_back’ in ‘fitsKeywords’, which is of non-class type ‘int’
 2784 |         fitsKeywords.push_back({"GPS_ET", GPSDataStartT[GPS_DATA_END_TS].text, "EndShutterTime"});
      |                      ^~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2788:22: error: request for member ‘push_back’ in ‘fitsKeywords’, which is of non-class type ‘int’
 2788 |         fitsKeywords.push_back({"GPS_NFLG", GPSHeader.now_flag, "NowFlag"});
      |                      ^~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2790:22: error: request for member ‘push_back’ in ‘fitsKeywords’, which is of non-class type ‘int’
 2790 |         fitsKeywords.push_back({"GPS_NS", GPSHeader.now_sec, "NowShutterSeconds"});
      |                      ^~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2792:22: error: request for member ‘push_back’ in ‘fitsKeywords’, which is of non-class type ‘int’
 2792 |         fitsKeywords.push_back({"GPS_NU", GPSHeader.now_us, 3, "NowShutterMicroSeconds"});
      |                      ^~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2794:22: error: request for member ‘push_back’ in ‘fitsKeywords’, which is of non-class type ‘int’
 2794 |         fitsKeywords.push_back({"GPS_NT", GPSDataStartT[GPS_DATA_NOW_TS].text, "NowShutterTime"});
      |                      ^~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2797:22: error: request for member ‘push_back’ in ‘fitsKeywords’, which is of non-class type ‘int’
 2797 |         fitsKeywords.push_back({"GPS_PPSC", GPSHeader.max_clock, "PPSCounter"});
      |                      ^~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2808:22: error: request for member ‘push_back’ in ‘fitsKeywords’, which is of non-class type ‘int’
 2808 |         fitsKeywords.push_back({"GPS_LONG", GPSHeader.longitude, 7, "GPS Longitude"});
      |                      ^~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2811:22: error: request for member ‘push_back’ in ‘fitsKeywords’, which is of non-class type ‘int’
 2811 |         fitsKeywords.push_back({"GPS_LAT", GPSHeader.latitude, 7, "GPS Latitude"});
      |                      ^~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2814:22: error: request for member ‘push_back’ in ‘fitsKeywords’, which is of non-class type ‘int’
 2814 |         fitsKeywords.push_back({"GPS_SEQ", GPSHeader.seqNumber, "Sequence Number"});
      |                      ^~~~~~~~~
/home/zac/Projects/indi-3rdparty/indi-qhy/qhy_ccd.cpp:2817:22: error: request for member ‘push_back’ in ‘fitsKeywords’, which is of non-class type ‘int’
 2817 |         fitsKeywords.push_back({"GPS_TMP", GPSHeader.tempNumber, "Temporary Sequence Number"});
      |                      ^~~~~~~~~
make[2]: *** [CMakeFiles/indi_qhy_ccd.dir/build.make:76: CMakeFiles/indi_qhy_ccd.dir/qhy_ccd.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:89: CMakeFiles/indi_qhy_ccd.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
zac@rpi1:~/Projects/build/indi-qhy/test $ 

**To Reproduce**
Exact steps to reproduce the behavior.

Follow instructions in README.md and indi-qhy and libqhy.

**Expected behavior**

Expected make to work

**Desktop (please complete the following information):**

 Raspberry Pi OS with desktop
Release date: July 4th 2024
System: 64-bit
Kernel version: 6.6
Debian version: 12 (bookworm)

Running on a Raspberry pi 4B

**Log Files**
Make sure to enable logging and include log files https://indilib.org/support/logs-submission.html

**Comment by knro** [comment]
You need to build and update indi first.
